name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest ruff black
        pip install -e .
        
    - name: Lint with ruff
      run: |
        ruff .
        
    - name: Check formatting with black
      run: |
        black --check .
        
    - name: Run tests (without API keys)
      run: |
        pytest tests/ -k "not api" 